services:
  db:
    image: postgres:16
    container_name: inventario_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: inventario
      POSTGRES_PASSWORD: inventario123
      POSTGRES_DB: inventario
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
